import { defineConfig } from "vitest/config";
import { resolve } from "node:path";

export default defineConfig({
  resolve: {
    alias: {
      "@": resolve(__dirname, "."),
    },
  },
  test: {
    environment: "node",
    setupFiles: ["vitest.setup.ts"],
    include: [
      "tests/terminalCapability*.test.ts",
      "tests/terminalToolExposure*.test.ts",
      "tests/terminalCapabilityPrompt*.test.ts",
      "tests/scheduleConflictSameCourse.test.ts",
      "tests/scheduleWeekExpression.test.ts",
      "tests/scheduleWeekStrict.test.ts",
      "tests/scheduleWeekIntegration.test.ts",
      "tests/scheduleImportCore.test.ts",
      "tests/timetableImportDomain.test.ts",
      "tests/timetableImportDraft.test.ts",
      "tests/timetableImportPreview.test.tsx",
      "tests/timetableImportRouting.test.ts",
      "tests/timetableImportNormalization.test.ts",
      "tests/timetableImportFinalHardening.test.tsx",
      "tests/aiOpenCodeGoMimoTimetableVisionSmoke.test.ts",
      "tests/focusControlCompact.test.tsx",
      "tests/sidebarChrome.test.ts",
      "tests/terminalStreaming.test.ts",
      "tests/terminalSecretRedaction.test.ts",
      "tests/kiroTerminalBlock.test.tsx",
      "tests/terminalLifecycle.test.ts",
      "tests/terminalStdin.test.ts",
      "tests/terminalPtyContract.test.ts",
      "tests/terminalAsyncLifecycle.test.ts",
      "tests/terminalPtyAgentIntegration.test.ts",
      "tests/terminalFinalHardening.test.ts",
      "tests/aiOpenCodeGoTerminalSmoke.test.ts",
      "tests/aiOpenCodeGoTerminalInteractiveSmoke.test.ts",
      "tests/extensionsRegistry.test.ts",
      "tests/extensionsPermissions.test.ts",
      "tests/permissionModelV2.test.ts",
      "tests/secretVault.test.ts",
      "tests/secretVaultProduction.test.ts",
      "tests/apiBoundary.test.ts",
      "tests/securityBaseline.test.ts",
      "tests/skillCore.test.ts",
      "tests/workflowTrace.test.ts",
      "tests/workflowSanitize.test.ts",
      "tests/workflowDistillSecurity.test.ts",
      "tests/invocationTrust.test.ts",
      "tests/kiroInvocationTrust.test.ts",
      "tests/mcpConnection.test.ts",
      "tests/mcpApproval.test.ts",
      "tests/mcpTrustBoundary.test.ts",
      "tests/inboxTrustBoundary.test.ts",
      "tests/workflowTurnSelection.test.ts",
      "tests/workflowDistillIntegration.test.ts",
      "tests/channelRegistry.test.ts",
      "tests/channelBrandPresentation.test.ts",
      "tests/channelConfig.test.ts",
      "tests/qqNormalize.test.ts",
      "tests/qqDedupe.test.ts",
      "tests/qqPolicy.test.ts",
      "tests/qqAdapter.test.ts",
      "tests/channelInboxIntegration.test.ts",
      "tests/qqSecretBoundary.test.ts",
      "tests/qqSdkContract.test.ts",
      "tests/qqTransportLifecycle.test.ts",
      "tests/qqInboxDelivery.test.ts",
      "tests/qqTestConnection.test.ts",
      "tests/qqMentionPolicy.test.ts",
      "tests/inboxDeliveryQueue.test.ts",
      "tests/inboxRendererReload.test.ts",
      "tests/inboxMultiAccount.test.ts",
      "tests/channelPersistence.test.ts",
      "tests/channelReplyContext.test.ts",
      "tests/channelSendApproval.test.ts",
      "tests/qqExplicitReply.test.ts",
      "tests/qqReplyTarget.test.ts",
      "tests/qqOutboundTrust.test.ts",
      "tests/qqOutboundIdempotency.test.ts",
      "tests/qqOutboundAntiLoop.test.ts",
      "tests/qqOutboundIpc.test.ts",
      "tests/qqReplyContextPropagation.test.ts",
      "tests/qqReplyDraft.test.ts",
      "tests/settingsRegistry.test.ts",
      // Kiro Sidecar Capsule V1 — jsdom via @vitest-environment
      "tests/kiroSidecarShell.test.tsx",
      "tests/kiroSidecarSize.test.ts",
      "tests/sidecarPosition.test.ts",
      "tests/kiroRuntime.test.ts",
      "tests/kiroSidecarMinimizedPosition.test.ts",
      "tests/kiroSidecarPreferences.test.ts",
      "tests/kiroSidecarCapsule.test.tsx",
      "tests/kiroSidecarHost.test.tsx",
      "tests/kiroStreamingHistory.test.ts",
      "tests/kiroStreamingPromotion.test.tsx",
      "tests/kiroSendControl.test.tsx",
      "tests/kiroMotionEmptyIntro.test.tsx",
      "tests/motionPreference.test.ts",
      "tests/titleBarWindowControls.test.tsx",
      "tests/inboxPanelLifecycle.test.tsx",
      "tests/extensionsSettingsLayout.test.tsx",
      "tests/desktopPreloadRuntimeContract.test.ts",
      "tests/desktopLocalApiCapability.test.ts",
      "tests/kiroChatTransport.test.ts",
      "tests/aiModelCatalogTransport.test.ts",
      "tests/kiroAISettingsTransport.test.ts",
      "tests/rendererOriginTrust.test.ts",
      "scripts/docx-compat/generate-fixtures.test.ts",
    ],
  },
});
