import { ChannelError } from "../errors";

export const OutboundErrorCodes = {
  CHANNEL_REPLY_CONTEXT_NOT_FOUND: "CHANNEL_REPLY_CONTEXT_NOT_FOUND",
  CHANNEL_REPLY_CONTEXT_EXPIRED: "CHANNEL_REPLY_CONTEXT_EXPIRED",
  CHANNEL_SEND_APPROVAL_NOT_FOUND: "CHANNEL_SEND_APPROVAL_NOT_FOUND",
  CHANNEL_SEND_APPROVAL_EXPIRED: "CHANNEL_SEND_APPROVAL_EXPIRED",
  CHANNEL_SEND_APPROVAL_USED: "CHANNEL_SEND_APPROVAL_USED",
  QQ_REPLY_CONTEXT_INVALID: "QQ_REPLY_CONTEXT_INVALID",
  QQ_REPLY_REJECTED: "QQ_REPLY_REJECTED",
  QQ_SEND_REJECTED: "QQ_SEND_REJECTED",
  QQ_SEND_UNCERTAIN: "QQ_SEND_UNCERTAIN",
} as const;

export function outboundError(code: keyof typeof OutboundErrorCodes, message: string): ChannelError {
  return new ChannelError(code as never, message);
}
